### ISSUE TITLE
[PE-D][Tester B] GUI is not updated for find command related to task and wedding

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F15-4/tp#311] opened 2024-11-08 21:41 UTC
![image.png](https://raw.githubusercontent.com/YANYAN-w/ped/main/files/9fe18624-bbcd-4a42-9f0e-ddfa5fd044ab.png)
when executing `find w/Tom`, unlike the find person will show a list of results containing the target string, the wedding list is not updated. would be better to make this command have similar behaviour as the find command related to person, so as to have better consistency.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: YANYAN-w/ped#11

**Comment by tingxuanp** [comment] 2024-11-09 07:37
invalid bug...?? I think this person thinks `find w/` searches weddings instead of people assigned to the wedding

**Comment by HanB1n** [comment] 2024-11-09 12:45
I think this is not a bug. We could maybe be more explicit in the UG to say that find only searches the People View?

**Closed** 2024-11-11 17:24 UTC
Labels: Rejected Bugs
